server:
  port: 8082
  servlet:
    context-path: /
  application:
    name: webclient-service
  thymeleaf:
    suffix: .html
eureka:
  instance:
    preferIpAddress: true

service:
  url:
    register: /user/create
    updateUser: /user/update
    forgotPassword: /user/forgotPassword
    login: /jwt/auth
    logout: /jwt/invalidate
    getUserDetails: /user/
  authServer: http://user-auth-service

env: local