server:
  port: 8082
  servlet:
    context-path: /
  application:
    name: webclient-service
  thymeleaf:
    suffix: .html
eureka:
  instance:
    preferIpAddress: true

service:
  url:
    register: /user/create
    updateUser: /user/update
    forgotPassword: /user/forgotPassword
    resetPassword: /user/resetPassword
    login: /jwt/auth
    logout: /jwt/invalidate
    getUserDetails: /user/
  authServer: http://user-auth-service
logging:
  level:
    root: INFO
env: local

hystrix:
  command:
    getProductServiceCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
      circuitBreaker:
        requestVolumeThreshold: 5
        sleepWindowInMilliseconds: 2000
        errorThresholdPercentage: 20
  threadpool:
    getProductServiceThreadPool:
      coreSize: 30
      maxQueueSize: 5