server:
  port: 8081

jwt:
  secret: myJWTSecret12345

logging:
  level:
    root: INFO

spring:
  application:
    name: user-auth-service
  config:
    import: "optional:configserver:"
    cloud:
      config:
        uri: http://config-server
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      
eureka:
  instance:
    preferIpAddress: true