server:
  port: 8081

jwt:
  secret: myJWTSecret12345

logging:
  level:
    root: DEBUG

spring:
  application:
    name: user-auth-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sayan
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      
eureka:
  instance:
    preferIpAddress: true